server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/app_submission?sslmode=disable
    username: root
    password: secretpwd
    driver-class-name: org.postgresql.Driver
  main:
    allow-bean-definition-overriding: true
  jpa:
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update  # Use update (or 'validate') or none in production, create-drop is useful for dev only 
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        id:
          new_generator_mappings: true
        globally_quoted_identifiers: true
        # Adding the Naming Strategy to ensure quoting
        hibernate.physical_naming_strategy: com.app.jpa.CustomPhysicalNamingStrategy

logging:
  level:
    org.springframework: ERROR
    com.app: DEBUG
    org.springframework.web.servlet.DispatcherServlet: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: "%d %p %c{1.} [%t] %m%n"
  file:
    name: /app/app.log  # Make sure logs are written to /app/app.log

