server:
  port: 8090

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/app_submission?sslmode=disable
    username: root
    password: secretpwd
    driver-class-name: org.postgresql.Driver
  main:
    allow-bean-definition-overriding: true
  jpa:
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update  # Use update or none in production, create-drop is useful for dev only 
                        # You can use 'update' or 'validate' instead of 'create-drop' depending on your needs
      use-new-id-generator-mappings: false

logging:
  level:
    org.springframework: ERROR
    com.app: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: "%d %p %c{1.} [%t] %m%n"
  file: app.log
